In [1]:
import numpy as np
from model_zambezi import ModelZambezi

model = ModelZambezi()

In [2]:
policy_input_parameters = np.loadtxt('../testDecisions/decisions_best_env.txt')
#ZambeziProblem.evaluate(policy_input_parameters)

In [3]:
model.evaluate(policy_input_parameters)

dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(['itezhitezhi', 'kafuegorgeupper', 'kafuegorgelower', 'kariba', 'cahorabassa'])
dict_keys(

[3168298.5928087803, 1.8422806210554217, 32.34865752757907]

In [1]:
{1:5, 2:4}[1]

5

In [7]:
model.reservoirs["cahorabassa"].release_vector

array([2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125,  985.90032016,  564.51804527,
       1216.91719744, 1995.40466452, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 1972.24529011, 1246.66988601,
       1012.29023576,  643.99838945,  468.78366477,  563.76003636,
       1565.5848051 , 2008.7773804 , 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 1883.72008688, 1172.66902882, 1989.81524532,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 2022.51321125, 2022.51321125, 2022.51321125,
       2022.51321125, 1911.3931905 ,  321.32606157,  372.89856

In [8]:
model.irr_districts["9"].normalised_deficit

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
model.reservoirs["cahorabassa"].actual_hydropower_production

array([1.25371472e-07, 1.19425350e-07, 1.36561503e-07, 1.52374614e-06,
       1.02824189e-05, 1.31927189e-07, 1.38362031e-07, 1.40266746e-07,
       1.35665763e-07, 1.40120148e-07, 1.35621057e-07, 1.40393409e-07,
       7.04750452e-06, 4.49057548e-06, 1.02318188e-05, 1.32328887e-07,
       1.39119687e-07, 4.26200175e-06, 1.01458644e-05, 1.40286148e-07,
       9.82908942e-06, 1.40040249e-07, 9.82410875e-06, 1.40518117e-07,
       2.55454323e-06, 7.50136846e-06, 1.03013139e-05, 1.33298974e-07,
       1.40364049e-07, 9.85111967e-06, 1.39394043e-07, 4.29077035e-06,
       9.81015058e-06, 1.40639320e-07, 9.85837145e-06, 1.39370169e-07,
       1.01360905e-05, 9.18999880e-06, 1.02208364e-05, 7.34065046e-06,
       1.02124119e-05, 1.00533942e-05, 1.32592653e-07, 1.40413109e-07,
       9.83646876e-06, 1.39759520e-07, 9.06836731e-06, 4.40887446e-06,
       1.01485396e-05, 8.68230677e-06, 7.14745992e-06, 9.96607202e-06,
       1.38172567e-07, 4.66089839e-06, 1.01741308e-05, 1.40387844e-07,
      

In [2]:
import pandas as pd

#list = pd.read_excel("../settings/settings_file.xlsx", sheet_name="ModelParameters")

In [ ]:
list

Parameter Name  \
0                   Simulation Horizon   
1                        Initial Month   
2                 Initial Total Inflow   
3             Number of Days per Month   
4  Itezhi-Itezhi Previous Two Releases   
5                      Reservoir Names   
6                      Catchment Names   
7            Irrigation District Names   

                                               Value    Unit  \
0                                                240  months   
1                                                  1    Dmnl   
2                                          1308.3372    m3/s   
3   [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]    days   
4                {-2: 59.67067857, -1: 101.73074194}    m3/3   
5  ["itezhitezhi", "kafuegorgeupper","kafuegorgel...    Dmnl   
6  ["Itt","KafueFlats","Ka","Cb","Cuando","Shire"...    Dmnl   
7           ["2", "3", "4", "5", "6", "7", "8", "9"]    Dmnl   

              in Python Data Type  
0    simulation_horizon       int  
1            init_month       int  
2           inflowTOT00     float  
3  nu_of_days_per_month  np.array  
4    ithezhitezhi_delay      dict  
5       reservoir_names      list  
6       catchment_names      list  
7    irr_district_names      list

In [2]:
new = pd.read_excel("../settings/settings_file.xlsx", sheet_name="Reservoirs")

In [3]:
new

Reservoir Name  Initial Storage(m3)  Hydroelectric Turbine Count  \
0      Itezhitezhi         3.644646e+09                            1   
1  KafueGorgeUpper         6.739174e+08                            1   
2  KafueGorgeLower         6.284000e+07                            1   
3           Kariba         1.238740e+11                            2   
4      Cahorabassa         2.239356e+10                            1   

  Max Turbine Flow    Efficiency Head Start Level  
0            [612]        [0.89]            [990]  
1            [252]        [0.61]            [580]  
2            [487]        [0.88]          [403.3]  
3      [1200, 840]  [0.48, 0.51]   [381.5, 383.5]  
4           [2260]        [0.73]            [203]

In [9]:
new["Reservoir Name"] = pd.Series(map(str.lower, new["Reservoir Name"]))

In [11]:
new.set_index("Reservoir Name")

Initial Storage(m3)  Hydroelectric Turbine Count  \
Reservoir Name                                                      
itezhitezhi             3.644646e+09                            1   
kafuegorgeupper         6.739174e+08                            1   
kafuegorgelower         6.284000e+07                            1   
kariba                  1.238740e+11                            2   
cahorabassa             2.239356e+10                            1   

                Max Turbine Flow    Efficiency Head Start Level  
Reservoir Name                                                   
itezhitezhi                [612]        [0.89]            [990]  
kafuegorgeupper            [252]        [0.61]            [580]  
kafuegorgelower            [487]        [0.88]          [403.3]  
kariba               [1200, 840]  [0.48, 0.51]   [381.5, 383.5]  
cahorabassa               [2260]        [0.73]            [203]

In [18]:
new.columns[-3:].values.tolist()

['Max Turbine Flow', 'Efficiency', 'Head Start Level']

In [19]:
"Max Turbine Flow".replace(" ", "_").lower()

'max_turbine_flow'

In [3]:
deneme = pd.read_excel("../settings/settings_file.xlsx", sheet_name="PolicyParameters")

In [4]:
deneme

splitpoints = deneme.loc[deneme["Parameter Name"] == "Name"].index

In [5]:
list(splitpoints)

[0]

In [6]:
splitpoints = splitpoints.values.tolist()

In [7]:
deneme
splitpoints[0]

0

In [8]:
dflist = list()
for i in range(len(splitpoints)):
    try:
        one_df = deneme.iloc[splitpoints[i]:splitpoints[i+1],:]
    except IndexError:
        one_df = deneme.iloc[splitpoints[i]:,:]
    dflist.append(one_df)


In [9]:
dflist[0]

Parameter Name                                              Value  Unit  \
0               Name                                            release   NaN   
1               Type                                              ncRBF   NaN   
2   Number of Inputs                                                  7   NaN   
3  Number of Outputs                                                  5   NaN   
4     Number of RBFs                                                 11   NaN   
5          Max Input  [5883000000.00,1178000000.00,180798000000.0000...   NaN   
6         Max Output  [7338.28210,2894.4600,11539.93658041603,15859....   NaN   
7          Min Input  [699000000.0,5000000.0,116054000000.0000, 3200...   NaN   
8         Min Output                                        [0,0,0,0,0]   NaN   

      in Python Data Type  
0          name       str  
1          type       str  
2      n_inputs       int  
3     n_outputs       int  
4  n_structures       int  
5     max_input  np.array  
6    max_output  np.array  
7     min_input  np.array  
8    min_output  np.array

In [32]:
import numpy as np
one_policy = dflist[0].copy()

input_dict = dict()
            
for _, row in one_policy.iterrows():
    key = row["in Python"]
    if row["Data Type"] != "str": value = eval(str(row["Value"]))
    else: value = row["Value"]
    if row["Data Type"] == "np.array": value = np.array(value)
    input_dict[key] = value

input_dict
# one_policy.loc[one_policy["Data Type"] == "np.array", "Value"] =\
#     pd.Series(map(lambda x: np.array(x), one_policy.\
#     loc[one_policy["Data Type"] == "np.array", "Value"]))

{'name': 'release',
 'type': 'ncRBF',
 'n_inputs': 7,
 'n_outputs': 5,
 'n_structures': 11,
 'max_input': array([5.8830000e+09, 1.1780000e+09, 1.8079800e+11, 5.1704000e+10,
        6.2840000e+07, 1.2000000e+01, 1.1213579e+04]),
 'max_output': array([ 7338.2821    ,  2894.46      , 11539.93658042, 15859.695586  ,
         4445.96752917]),
 'min_input': array([6.99000e+08, 5.00000e+06, 1.16054e+11, 3.20000e+07, 1.09500e+07,
        1.00000e+00, 0.00000e+00]),
 'min_output': array([0, 0, 0, 0, 0])}

In [31]:
one_policy


Parameter Name                                              Value  Unit  \
0               Name                                            release   NaN   
1               Type                                              ncRBF   NaN   
2   Number of Inputs                                                  7   NaN   
3  Number of Outputs                                                  5   NaN   
4     Number of RBFs                                                 11   NaN   
5          Max Input  [5883000000.00,1178000000.00,180798000000.0000...   NaN   
6         Max Output  [7338.28210,2894.4600,11539.93658041603,15859....   NaN   
7          Min Input  [699000000.0,5000000.0,116054000000.0000, 3200...   NaN   
8         Min Output                                        [0,0,0,0,0]   NaN   

      in Python Data Type  (2, Value)  (3, Value)  (4, Value)  
0          name       str           7           5          11  
1          type       str           7           5          11  
2      n_inputs       int           7           5          11  
3     n_outputs       int           7           5          11  
4  n_structures       int           7           5          11  
5     max_input  np.array           7           5          11  
6    max_output  np.array           7           5          11  
7     min_input  np.array           7           5          11  
8    min_output  np.array           7           5          11

In [13]:
dflist[0].loc[df,"Value"] = pd.Series(map(lambda x: eval(x), dflist[0]["Value"]))

NameError: name 'release' is not defined

In [16]:
eval(3)

TypeError: eval() arg 1 must be a string, bytes or code object

In [3]:
from smash import Policy

trial = Policy()
inputdict = {"name": "release", "type": "ncRBF", "n_inputs": 5, "n_outputs": 3, "n_structures": 8}

trial.add_policy_function(**inputdict)